[project]
name = "partdb"
version = "0.1.0"
description = "A tool for keeping track of where parts are stored."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.7",
    "openai>=1.55.0",
    "psycopg>=3.2.3",
]
[project.scripts]
partdb = "partdb.main:cli"
